spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://veggiehunter-springboot-webservice.cnrhvv9ptkr7.ap-northeast-2.rds.amazonaws.com:3306/veggiehunter
    username: veggiehunter
    password: veggiehunter5
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql:
        dialect: org.hibernate.dialect.MySQL8Dialect
    database-platform: mysql
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration