spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: GmSaP98VJ8I5_RfxTJjv
            client-secret: 5NUvPPHoY_
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
            scope: name,email,profile_image
            client-name: Naver
            provider: naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://veggiehunter-springboot-webservice.cnrhvv9ptkr7.ap-northeast-2.rds.amazonaws.com:3306/veggiehunter
    username: veggiehunter
    password: veggiehunter5
  session:
    store-type: jdbc
    jdbc.initialize-schema: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql:
        dialect: org.hibernate.dialect.MySQL8Dialect
    database-platform: mysql
