// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBimIityDw3UQeSULC2fqpY5wQKAgcgH38',
    appId: '1:1068133138181:web:4f722535e409a511d8416c',
    messagingSenderId: '1068133138181',
    projectId: 'vegehunter-3bd4e',
    authDomain: 'vegehunter-3bd4e.firebaseapp.com',
    storageBucket: 'vegehunter-3bd4e.appspot.com',
    measurementId: 'G-M0K65CRZJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2xxPI7w_N_BMOXv4PPTK9Z_meYG5Ch_U',
    appId: '1:1068133138181:android:8169b4c31b8ba5fad8416c',
    messagingSenderId: '1068133138181',
    projectId: 'vegehunter-3bd4e',
    storageBucket: 'vegehunter-3bd4e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoROeWR5KXhZCDoRXZTJWSQ3Lta_IP2fo',
    appId: '1:1068133138181:ios:a03fab494b6d9307d8416c',
    messagingSenderId: '1068133138181',
    projectId: 'vegehunter-3bd4e',
    storageBucket: 'vegehunter-3bd4e.appspot.com',
    iosBundleId: 'com.example.vegetable',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoROeWR5KXhZCDoRXZTJWSQ3Lta_IP2fo',
    appId: '1:1068133138181:ios:7d5d0556850bb658d8416c',
    messagingSenderId: '1068133138181',
    projectId: 'vegehunter-3bd4e',
    storageBucket: 'vegehunter-3bd4e.appspot.com',
    iosBundleId: 'com.example.vegetable.RunnerTests',
  );
}
